Pass the audiodevice to handle setup with multiple soundcard
4br3mm0rd/mpyg321 pull request #17
Opened 2021-07-09 15:28 UTC by stefets

Hi Emmanuel, 
Would like to push this one first.

2021-07-11 09:36 UTC, 4br3mm0rd requested changes

2021-07-11 09:36 UTC, 4br3mm0rd commented on mpyg321/mpyg321.py
> +        if audiodevice:
I would just write this as a one-liner (like the previous one) for readability

2021-07-11 09:36 UTC, 4br3mm0rd commented on mpyg321/mpyg321.py
>          self.player = pexpect.spawn(str(player) + " " + args)
What happens when the audiodevice doesn't exist? Maybe we should pexpect for this kind of error and handle it? What do you think?

2021-07-11 13:25 UTC, stefets commented on mpyg321/mpyg321.py
>          self.player = pexpect.spawn(str(player) + " " + args)
I agree, it's not robust enough.

In the mpg123 world, If I pass an invalid device, pexpect failed and the EOF error happen like in #12 and I have not found a fix at this moment.

Maybe we can check the exitstatus property; the value is None when all is good; in this use case, the exitstatus equals 255.

Since we add a new parameter and it's possible to add new parameters in the future,  maybe a try / except is welcome here in the second spawn in set_player ?

Suggestion
```
args += " --audiodevice " + audiodevice if audiodevice else ""
try
        self.player = pexpect.spawn(str(player) + " " + args)
except pexpect.exceptions.EOF
        raise MPyg321AdequateError("Adequate message")
```

This is the output with an incorrect audiodevice
```
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x76203850>
command: /usr/local/bin/mpg123
args: ['/usr/local/bin/mpg123', '--remote', '--audiodevice', 'hw:1,1']
buffer (last 100 chars): b''
before (last 100 chars): b'[src/mpg123.c:check_fatal_output():332] error: out123 error 3: failure loading driver module\r\n\x1b[?25h'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 255
flag_eof: True
pid: 2343
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'@P 0')
    1: re.compile(b'@P 1')
    2: re.compile(b'@P 2')
    3: re.compile(b'@P 3')
    4: re.compile(b'@E *')

```

2021-07-12 21:45 UTC, 4br3mm0rd commented on mpyg321/mpyg321.py
>          self.player = pexpect.spawn(str(player) + " " + args)
OK, I feel like we can take care of this in another version, I'll merge this PR in the meantime (and we already have an open issue for #12

2021-07-12 21:46 UTC, merged